version: '3'
services:
  web:
    image: gemanueldev/recognition-django  # Use a imagem que você construiu
    container_name: recognition_django
    ports:
      - "5000:5000"
    environment:
      - DEBUG=True
      - SECRET_KEY=mysecretkey
    command: sh -c "python manage.py runserver 0.0.0.0:5000"
